# Generated by Django 2.1.7 on 2019-03-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190324_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.Candidate'),
        ),
    ]
